/**
 * Bonds Calculator Shared Export Utilities
 * PDF, print, and share helpers
 */

// ===== 1. Update Share Link =====
function updateShareLink(inputId, params) {
  var url = new URL(window.location.href);
  for (var key in params) {
    if (params[key] !== undefined && params[key] !== null && params[key] !== '') {
      url.searchParams.set(key, params[key]);
    }
  }
  var input = document.getElementById(inputId);
  if (input) input.value = url.toString();
  return url.toString();
}

// ===== 2. Copy Share Link =====
function copyShareLink(inputId) {
  var input = document.getElementById(inputId);
  if (!input) return;
  input.select();
  if (document.execCommand('copy')) {
    if (window.BondsUI && BondsUI.toast) BondsUI.toast('✅ تم نسخ الرابط!', 'success');
  }
}

// ===== 3. Export Element to PDF (jsPDF + html2canvas) =====
async function exportElementToPDF(options) {
  options = options || {};
  var elementId = options.elementId;
  var filename = options.filename || 'report.pdf';
  var bgColor = options.bgColor || '#ffffff';
  var scale = options.scale || 2;

  var section = document.getElementById(elementId);
  if (!section || section.style.display === 'none') {
    if (window.BondsUI && BondsUI.toast) BondsUI.toast('⚠️ احسب النتائج أولاً', 'warning');
    return false;
  }

  await Promise.all([
    loadLib('https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js', 'jspdf'),
    loadLib('https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js')
  ]);

  if (typeof html2canvas === 'undefined') {
    if (window.BondsUI && BondsUI.toast) BondsUI.toast('❌ فشل تحميل html2canvas', 'error');
    return false;
  }

  var canvas = await html2canvas(section, { scale: scale, backgroundColor: bgColor, useCORS: true });
  var imgData = canvas.toDataURL('image/png');
  var { jsPDF } = window.jspdf;
  var pdf = new jsPDF('p', 'mm', 'a4');
  var imgWidth = 210;
  var pageHeight = 297;
  var imgHeight = canvas.height * imgWidth / canvas.width;
  var heightLeft = imgHeight;
  var position = 0;
  pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
  heightLeft -= pageHeight;
  while (heightLeft >= 0) {
    position = heightLeft - imgHeight;
    pdf.addPage();
    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;
  }
  pdf.save(filename);
  return true;
}

// ===== 4. Open Styled Print Window =====
function openPrintWindow(options) {
  options = options || {};
  var content = options.content || '';
  var title = options.title || 'تقرير';
  var headerTitle = options.headerTitle || title;
  var autoPrint = options.autoPrint !== false;
  var lang = options.lang || 'ar';
  var dir = lang === 'en' ? 'ltr' : 'rtl';
  var dateLocale = lang === 'en' ? 'en-US' : 'ar-SA';
  var siteName = lang === 'en' ? 'Bonds Financial Consulting' : 'بوندز للاستشارات المالية';
  var disclaimer = lang === 'en'
    ? 'This report is for estimation purposes only and does not replace licensed financial advice.<br>Generated by bonds-global.com'
    : 'هذا التقرير للأغراض التقديرية فقط ولا يغني عن استشارة مالية مرخصة.<br>تم إنشاؤه بواسطة bonds-global.com';
  var logoHtml = options.hideLogo ? '' : '<img src="https://bonds-global.com/assets/bonds-logo.svg" style="width:56px;height:auto;margin-bottom:6px;" alt="Bonds" onerror="this.style.display=\'none\'"/>';
  var h1Text = lang === 'en' ? 'Bonds' : 'بوندز';

  var printWindow = window.open('', '_blank');
  if (!printWindow) {
    if (window.BondsUI && BondsUI.toast) {
      var msg = lang === 'en'
        ? '⚠️ Popup blocked. Please allow popups for this site.'
        : '⚠️ تم حظر النافذة المنبثقة. يرجى السماح بالنوافذ المنبثقة لهذا الموقع.';
      BondsUI.toast(msg, 'warning');
    }
    return null;
  }

  printWindow.document.write(
    '<!DOCTYPE html>' +
    '<html dir="' + dir + '">' +
    '<head>' +
    '<meta charset="UTF-8">' +
    '<title>' + title + ' - Bonds</title>' +
    '<style>' +
    '@import url("https://fonts.googleapis.com/css2?family=Vazirmatn:wght@400;600;700;800;900&display=swap");' +
    '@import url("https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&display=swap");' +
    'body { font-family: ' + (lang === 'en' ? 'Inter' : 'Vazirmatn') + ', Arial, sans-serif; background: #fff; color: #1a1a1a; padding: 32px; max-width: 1100px; margin: 0 auto; line-height: 1.6; }' +
    'h1 { color: #0a0f1a; margin: 0; font-size: 22px; text-align: center; font-weight: 900; }' +
    '.header { text-align: center; border-bottom: 3px solid #d4a853; padding-bottom: 16px; margin-bottom: 24px; }' +
    '.header p { color: #555; margin: 4px 0; font-size: 14px; }' +
    '.header .site-name { font-size: 14px; font-weight: 700; color: #444; letter-spacing: 0.3px; }' +
    '.header .report-title { font-size: 16px; font-weight: 700; color: #222; margin-top: 6px; }' +
    '.header .date-line { color: #888; font-size: 12px; margin-top: 4px; }' +
    'h2 { color: #b88a3a; border-bottom: 1px solid #e5e5e5; padding-bottom: 6px; margin-top: 28px; font-size: 17px; font-weight: 800; }' +
    'h3 { color: #444; font-size: 15px; margin-top: 18px; margin-bottom: 8px; font-weight: 700; }' +
    'table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 13px; }' +
    'th, td { padding: 10px 12px; border: 1px solid #ddd; text-align: ' + (lang === 'en' ? 'left' : 'right') + '; }' +
    'th { background: #f8f5ef; font-weight: 700; color: #333; }' +
    'tr:nth-child(even) { background: #fafafa; }' +
    'td.num { text-align: ' + (lang === 'en' ? 'right' : 'left') + '; font-family: monospace; direction: ltr; }' +
    '.footer { font-size: 11px; color: #999; border-top: 1px solid #ddd; padding-top: 12px; margin-top: 30px; text-align: center; line-height: 1.8; }' +
    '.chart-img { max-width: 100%; height: auto; margin: 15px 0; page-break-inside: avoid; }' +
    '.metric-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 14px; margin: 16px 0; }' +
    '.metric-item { background: #f8f5ef; border-radius: 8px; padding: 14px; text-align: center; }' +
    '.metric-item .label { font-size: 12px; color: #666; font-weight: 600; margin-bottom: 4px; }' +
    '.metric-item .value { font-size: 18px; font-weight: 800; color: #b88a3a; }' +
    '.scenario-row { display: grid; grid-template-columns: repeat(3, 1fr); gap: 14px; margin: 16px 0; }' +
    '.scenario-item { border-radius: 8px; padding: 14px; text-align: center; border-top: 3px solid #ccc; }' +
    '.scenario-item.pess { border-top-color: #ef4444; background: #fef2f2; }' +
    '.scenario-item.exp { border-top-color: #d4a853; background: #fffbf0; }' +
    '.scenario-item.opt { border-top-color: #22c55e; background: #f0fdf4; }' +
    '.scenario-item .label { font-size: 12px; font-weight: 700; margin-bottom: 4px; text-transform: uppercase; }' +
    '.scenario-item .value { font-size: 18px; font-weight: 800; }' +
    '.scenario-item .desc { font-size: 12px; color: #666; margin-top: 4px; }' +
    '.verdict-box { padding: 18px; border-radius: 10px; margin: 16px 0; text-align: center; }' +
    '.verdict-box.profit { background: #f0fdf4; border: 1px solid #86efac; }' +
    '.verdict-box.loss { background: #fef2f2; border: 1px solid #fca5a5; }' +
    '.verdict-box.warn { background: #fffbeb; border: 1px solid #fcd34d; }' +
    '@media print { body { padding: 20px; } .chart-img { max-height: 280px; } }' +
    '</style>' +
    '</head>' +
    '<body>' +
    '<div class="header">' +
    logoHtml +
    '<h1>' + h1Text + '</h1>' +
    '<p class="site-name">' + siteName + '</p>' +
    '<p class="report-title">' + headerTitle + '</p>' +
    '<p class="date-line">' + new Date().toLocaleDateString(dateLocale, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }) + '</p>' +
    '</div>' +
    content +
    '<div class="footer">' +
    disclaimer +
    '</div>' +
    (autoPrint ? '<script>window.onload = function() { setTimeout(function() { window.print(); }, 800); };</scr' + 'ipt>' : '') +
    '</body>' +
    '</html>'
  );
  printWindow.document.close();
  return printWindow;
}
