/**
 * Build styles.css by inlining the CSS partials.
 * Removes render-blocking @import chains while preserving cascade layers.
 * Run this whenever styles/tokens.css, base.css, components.css, utilities.css or select-reset.css change.
 */
const fs = require('fs');
const path = require('path');

const STYLES_DIR = path.resolve(__dirname, '..', 'styles');
const OUT_FILE = path.resolve(__dirname, '..', 'styles.css');

const PARTIALS = [
  { file: 'tokens.css', layer: 'tokens' },
  { file: 'base.css', layer: 'base' },
  { file: 'components.css', layer: 'components' },
  { file: 'utilities.css', layer: 'utilities' },
  { file: 'select-reset.css', layer: 'components' },
];

let output = '/* Generated by scripts/build-css.js — do not edit manually. */\n';

for (const { file, layer } of PARTIALS) {
  const content = fs.readFileSync(path.join(STYLES_DIR, file), 'utf8');
  output += `\n/* === ${file} === */\n`;
  output += `@layer ${layer} {\n${content}\n}\n`;
}

function minifyCss(css) {
  return css
    // Remove comments
    .replace(/\/\*[\s\S]*?\*\//g, '')
    // Collapse whitespace
    .replace(/\s+/g, ' ')
    // Remove spaces around selectors/operators
    .replace(/\s*([{}:;,>~+\[\]\(\)])/g, '$1')
    .replace(/([{}:;,>~+\[\]\(\)])\s*/g, '$1')
    // Remove leading/trailing whitespace
    .trim();
}

output = minifyCss(output);

fs.writeFileSync(OUT_FILE, output);
console.log(`✓ Built ${OUT_FILE} (${(fs.statSync(OUT_FILE).size / 1024).toFixed(1)} KB)`);
