#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import re

with open('en/calculators/feasibility-template.html', 'r', encoding='utf-8') as f:
    content = f.read()

replacements = [
    ('lang="ar" dir="rtl"', 'lang="en" dir="ltr"'),
    ("'Vazirmatn'", "'Inter'"),
    ('نموذج دراسة الجدوى المتكامل | بوندز', 'Integrated Feasibility Study | Bonds'),
    ('نموذج دراسة جدوى احترافي متكامل: PESTLE، SWOT، تحليل مالي، تدفق نقدي، سيناريوهات. مجاني من بوندز.', 'Professional integrated feasibility study: PESTLE, SWOT, financial analysis, cash flow, scenarios. Free from Bonds.'),
    ('نموذج دراسة الجدوى المتكامل | بوندز', 'Integrated Feasibility Study | Bonds'),
    ('نموذج دراسة جدوى احترافي متكامل: PESTLE، SWOT، تحليل مالي، تدفق نقدي، سيناريوهات.', 'Professional integrated feasibility study: PESTLE, SWOT, financial analysis, cash flow, scenarios.'),
    # Nav
    ('الرئيسية</a>', 'Home</a>'),
    ('عن بوندز</a>', 'About</a>'),
    ('الخدمات', 'Services'),
    ('التحليل المالي', 'Financial Analysis'),
    ('إدارة التدفقات النقدية', 'Cash Flow Management'),
    ('دراسات الجدوى', 'Feasibility Studies'),
    ('نقطة التعادل', 'Break-Even'),
    ('الحاسبات', 'Calculators'),
    ('تدفق النقد</a>', 'Cash Flow</a>'),
    ('تسعير المنتج</a>', 'Product Pricing</a>'),
    ('القرض والتمويل</a>', 'Loan & Finance</a>'),
    ('المطاعم والسحابي</a>', 'Restaurants & Cloud</a>'),
    ('هندسة المنيو</a>', 'Menu Engineering</a>'),
    ('جدوى المطعم</a>', 'Restaurant Feasibility</a>'),
    ('تحليل الفواتير</a>', 'Invoice Analyzer</a>'),
    ('نموذج دراسة الجدوى</a>', 'Feasibility Study</a>'),
    ('المدونة</a>', 'Blog</a>'),
    ('الأسئلة</a>', 'FAQ</a>'),
    ('تواصل</a>', 'Contact</a>'),
    ('EN</a>', 'AR</a>'),
    ('EN"', 'AR"'),
    ('تبديل الوضع', 'Toggle Theme'),
    ('القائمة', 'Menu'),
    # Toolbar
    ('طباعة / PDF', 'Print / PDF'),
    ('مسح الكل', 'Clear All'),
    ('حفظ مسودة', 'Save Draft'),
    ('استرجاع مسودة', 'Load Draft'),
    ('تصدير Excel', 'Export Excel'),
    ('تم حفظ المسودة بنجاح ✅', 'Draft saved successfully ✅'),
    ('لا توجد مسودة محفوظة', 'No saved draft found'),
    ('تم استرجاع المسودة ✅', 'Draft loaded successfully ✅'),
    ('هل أنت متأكد من مسح جميع البيانات؟', 'Are you sure you want to clear all data?'),
    # Cover
    ('نموذج دراسة الجدوى المتكامل', 'Integrated Feasibility Study'),
    ('اسم المشروع / النشاط', 'Project / Business Name'),
    ('مثال: مطعم الذواقة', 'e.g. Al-Thawaqa Restaurant'),
    ('اسم صاحب النشاط', 'Owner Name'),
    ('الشكل القانوني', 'Legal Form'),
    ('مؤسسة فردية / شركة ذات مسؤولية محدودة', 'Sole Proprietorship / LLC'),
    ('تاريخ الإعداد', 'Preparation Date'),
    ('فكرة المشروع بجملة واحدة', 'Project Idea in One Sentence'),
    ('وصف مختصر لفكرة المشروع...', 'Brief description of the project idea...'),
    ('المبلغ المستثمر المتوقع (ريال)', 'Expected Investment (SAR)'),
    # Page 1 Vision
    ('نموذج دراسة الجدوى — الرؤية', 'Feasibility Study — Vision'),
    ('الرؤية والرسالة والأهداف', 'Vision, Mission & Objectives'),
    ('لماذا وجد المشروع وماذا يسعى لتحقيقه', 'Why the project exists and what it aims to achieve'),
    ('الرؤية (Vision) — إلى أين تتجه بعد 5-10 سنوات؟', 'Vision — Where do you see yourself in 5-10 years?'),
    ('رؤية طموحة ومحددة للمستقبل...', 'Ambitious and specific vision for the future...'),
    ('الرسالة (Mission) — ما قيمتك الأساسية؟', 'Mission — What is your core value?'),
    ('الغرض الأساسي من وجود المشروع...', 'The fundamental purpose of the project...'),
    ('الأهداف SMART', 'SMART Objectives'),
    ('Specific, Measurable, Achievable, Relevant, Time-bound...\nمثال: تحقيق 100 ألف ريال إيراد شهري خلال 12 شهر', 'Specific, Measurable, Achievable, Relevant, Time-bound...\nExample: Achieve 100K SAR monthly revenue within 12 months'),
    ('نقاط التمايز الأساسية (USP)', 'Unique Selling Propositions (USP)'),
    ('ما الذي يجعلك فريداً ومختلفاً عن كل المنافسين؟', 'What makes you unique and different from all competitors?'),
    # Page 2 Summary
    ('نموذج دراسة الجدوى — الملخص', 'Feasibility Study — Summary'),
    ('الملخص التنفيذي', 'Executive Summary'),
    ('نظرة عامة على كامل الدراسة (يُفضل كتابته آخراً)', 'Overview of the entire study (best written last)'),
    ('ملخص المشروع (3-5 أسطر)', 'Project Summary (3-5 lines)'),
    ('نظرة شاملة: الفكرة، السوق، الفرصة، والنتائج المتوقعة...', 'Comprehensive overview: idea, market, opportunity, expected results...'),
    ('رأس المال المطلوب (ريال)', 'Required Capital (SAR)'),
    ('فترة الاسترداد (شهر)', 'Payback Period (months)'),
    ('سيُحسب تلقائياً', 'Will be calculated automatically'),
    ('العائد المتوقع ROI (%)', 'Expected ROI (%)'),
    ('الوحدات الشهرية المتوقعة', 'Expected Monthly Units'),
    ('عدد الوظائف المتوقع', 'Expected Jobs'),
    ('حجم السوق المستهدف (ريال)', 'Target Market Size (SAR)'),
    # Page 3 Products
    ('نموذج دراسة الجدوى — المنتجات', 'Feasibility Study — Products'),
    ('وصف المنتجات والخدمات', 'Products & Services Description'),
    ('ما تقدمه وكيف يستفيد العملاء', 'What you offer and how customers benefit'),
    ('وصف المنتج/الخدمة الأساسية', 'Primary Product/Service Description'),
    ('صف جذرياً ما تبيعه...', 'Describe fundamentally what you sell...'),
    ('بطاقات المنتجات', 'Product Cards'),
    ('اسم المنتج', 'Product Name'),
    ('السعر (ريال)', 'Price (SAR)'),
    ('التكلفة المتغيرة', 'Variable Cost'),
    ('هامش المساهمة', 'Contribution Margin'),
    ('القيمة المضافة', 'Added Value'),
    ('ما الذي يميزك؟', 'What differentiates you?'),
    ('فائدة العميل', 'Customer Benefit'),
    ('الفائدة المباشرة...', 'Direct benefit...'),
    # Page 4 Market Analysis
    ('نموذج دراسة الجدوى — تحليل السوق', 'Feasibility Study — Market Analysis'),
    ('تحليل بيئة المشروع', 'Project Environment Analysis'),
    ('PESTLE + SWOT + قوى بورتر + شخصية العميل', 'PESTLE + SWOT + Porter\'s Forces + Customer Persona'),
    ('أ. تحليل PESTLE', 'A. PESTLE Analysis'),
    ('سياسي (Political)', 'Political'),
    ('القوانين، الدعم الحكومي، الاستقرار...', 'Laws, government support, stability...'),
    ('اقتصادي (Economic)', 'Economic'),
    ('النمو، التضخم، القدرة الشرائية...', 'Growth, inflation, purchasing power...'),
    ('اجتماعي (Social)', 'Social'),
    ('الثقافة، التركيبة السكانية، الاتجاهات...', 'Culture, demographics, trends...'),
    ('تكنولوجي (Technological)', 'Technological'),
    ('الابتكار، الأتمتة، التحول الرقمي...', 'Innovation, automation, digital transformation...'),
    ('قانوني (Legal)', 'Legal'),
    ('التراخيص، الضرائب، حماية المستهلك...', 'Licenses, taxes, consumer protection...'),
    ('بيئي (Environmental)', 'Environmental'),
    ('الاستدامة، التغير المناخي، الموارد...', 'Sustainability, climate change, resources...'),
    ('ب. تحليل SWOT', 'B. SWOT Analysis'),
    ('✅ نقاط القوة (Strengths)', '✅ Strengths'),
    ('ما تمتلكه من ميزات داخلية...', 'Internal advantages you possess...'),
    ('⚠️ نقاط الضعف (Weaknesses)', '⚠️ Weaknesses'),
    ('ما تحتاج لتحسينه داخلياً...', 'What needs internal improvement...'),
    ('🌟 الفرص (Opportunities)', '🌟 Opportunities'),
    ('عوامل خارجية يمكن الاستفادة منها...', 'External factors to capitalize on...'),
    ('⛔ التهديدات (Threats)', '⛔ Threats'),
    ('عوامل خارجية قد تؤثر سلباً...', 'External factors that may negatively impact...'),
    ('ج. تحليل قوى بورتر التنافسية', 'C. Porter\'s Five Forces'),
    ('القوة', 'Force'),
    ('الشدة (1-5)', 'Intensity (1-5)'),
    ('التوضيح', 'Explanation'),
    ('قوة المنافسين الحاليين', 'Competitive Rivalry'),
    ('عدد المنافسين، حدة التنافس...', 'Number of competitors, intensity...'),
    ('تهديد الداخلين الجدد', 'Threat of New Entrants'),
    ('حواجز الدخول، التراخيص...', 'Barriers to entry, licenses...'),
    ('قوة الموردين', 'Bargaining Power of Suppliers'),
    ('عدد الموردين، بدائلهم...', 'Number of suppliers, alternatives...'),
    ('قوة المشترين', 'Bargaining Power of Buyers'),
    ('خيارات العميل، حساسية السعر...', 'Customer options, price sensitivity...'),
    ('تهديد البدائل', 'Threat of Substitutes'),
    ('منتجات/خدمات بديلة...', 'Alternative products/services...'),
    ('د. شخصية العميل المثالية (Persona)', 'D. Ideal Customer Persona'),
    ('العمر / الجنس / الموقع', 'Age / Gender / Location'),
    ('مثال: 25-40 سنة، ذكور وإناث، الرياض', 'e.g. 25-40 years, male & female, Riyadh'),
    ('الدخل الشهري التقديري', 'Estimated Monthly Income'),
    ('5,000 - 15,000 ريال', '5,000 - 15,000 SAR'),
    ('الاحتياجات والآلام', 'Needs & Pain Points'),
    ('ما يعانون منه ويحتاجون لحله', 'What they suffer from and need solved'),
    # Page 5 Marketing
    ('نموذج دراسة الجدوى — التسويق', 'Feasibility Study — Marketing'),
    ('استراتيجية التسويق (4Ps)', 'Marketing Strategy (4Ps)'),
    ('خطة واضحة للوصول إلى العميل وتحويله', 'Clear plan to reach and convert customers'),
    ('المنتج (Product) — ما تبيعه وكيف تُقدمه', 'Product — What you sell and how you present it'),
    ('العبوة، الجودة، الخدمات الملحقة، الضمان...', 'Packaging, quality, ancillary services, warranty...'),
    ('السعر (Price) — استراتيجية التسعير', 'Price — Pricing strategy'),
    ('تسعير قيمة، تنافسي، اختراقي، فاخر...', 'Value-based, competitive, penetration, premium...'),
    ('السعر المتوقع للوحدة (ريال)', 'Expected Unit Price (SAR)'),
    ('الكمية المتوقعة شهرياً', 'Expected Monthly Quantity'),
    ('المكان (Place) — قنوات البيع والتوزيع', 'Place — Sales and distribution channels'),
    ('منصات توصيل، موقع فعلي، متجر إلكتروني، وكلاء...', 'Delivery platforms, physical location, e-store, agents...'),
    ('الترويج (Promotion) — خطة الوصول', 'Promotion — Reach plan'),
    ('السوشيال ميديا، الإعلانات المدفوعة، التسويق بالمحتوى، العروض الترويجية...', 'Social media, paid ads, content marketing, promotions...'),
    ('ميزانية التسويق الشهرية', 'Monthly Marketing Budget'),
    ('تكلفة اكتساب عميل (CAC)', 'Customer Acquisition Cost (CAC)'),
    # Page 6 Operations
    ('نموذج دراسة الجدوى — التشغيل', 'Feasibility Study — Operations'),
    ('خطة التشغيل والجدول الزمني', 'Operations Plan & Timeline'),
    ('كيف ستُدير العمليات يومياً وشهرياً', 'How you will manage operations daily and monthly'),
    ('موقع النشاط', 'Business Location'),
    ('المدينة، الحي، المساحة، الإيجار السنوي...', 'City, district, area, annual rent...'),
    ('ساعات العمل', 'Working Hours'),
    ('مثال: 8 صباحاً - 12 ليلاً، 7 أيام/أسبوع', 'e.g. 8 AM - 12 AM, 7 days/week'),
    ('عملية الإنتاج/الخدمة خطوة بخطوة', 'Production/Service Process Step by Step'),
    ('1. استلام الطلب → 2. التحضير → 3. التغليف → 4. التوصيل...', '1. Receive order → 2. Prepare → 3. Package → 4. Deliver...'),
    ('الجدول الزمني التفصيلي', 'Detailed Timeline'),
    ('المهمة', 'Task'),
    ('التاريخ المتوقع', 'Expected Date'),
    ('المسؤول', 'Responsible'),
    ('الحالة</th>', 'Status</th>'),
    ('إتمام الدراسة', 'Complete Study'),
    ('قيد التنفيذ', 'In Progress'),
    ('الحصول على التمويل', 'Funding Acquisition'),
    ('استخراج التراخيص', 'Obtain Licenses'),
    ('تجهيز الموقع', 'Site Preparation'),
    ('التوظيف', 'Hiring'),
    ('الافتتاح التجريبي', 'Soft Launch'),
    ('الافتتاح الرسمي', 'Grand Opening'),
    # Page 7 Legal
    ('نموذج دراسة الجدوى — القانون', 'Feasibility Study — Legal'),
    ('التراخيص والقوانين والتأمين', 'Licenses, Laws & Insurance'),
    ('الالتزامات التنظيمية والحماية القانونية', 'Regulatory obligations and legal protection'),
    ('التراخيص المطلوبة', 'Required Licenses'),
    ('اسم الترخيص', 'License Name'),
    ('الجهة المصدرة', 'Issuing Authority'),
    ('التكلفة (ريال)', 'Cost (SAR)'),
    ('مدة الإصدار', 'Issuance Duration'),
    ('سجل تجاري', 'Commercial Registration'),
    ('وزارة التجارة', 'Ministry of Commerce'),
    ('1-3 أيام', '1-3 days'),
    ('رخصة بلدية', 'Municipal License'),
    ('البلدية', 'Municipality'),
    ('2-4 أسابيع', '2-4 weeks'),
    ('تصريح دفاع مدني', 'Civil Defense Permit'),
    ('الدفاع المدني', 'Civil Defense'),
    ('1 أسبوع', '1 week'),
    ('شهادة صحية', 'Health Certificate'),
    ('3-5 أيام', '3-5 days'),
    ('التأمينات المطلوبة', 'Required Insurances'),
    ('تأمين الممتلكات، تأمين المسؤولية المدنية، تأمين الموظفين...', 'Property insurance, liability insurance, employee insurance...'),
    ('الالتزامات الضريبية المتوقعة', 'Expected Tax Obligations'),
    ('VAT 15%، Zakat 2.5%، ضريبة الدخل إن وجدت...', 'VAT 15%, Zakat 2.5%, income tax if applicable...'),
    # Page 8 HR
    ('نموذج دراسة الجدوى — الموارد البشرية', 'Feasibility Study — HR'),
    ('الموارد البشرية', 'Human Resources'),
    ('الهيكل التنظيمي والقوى العاملة المطلوبة', 'Organizational structure and required workforce'),
    ('الهيكل التنظيمي', 'Organizational Structure'),
    ('من يُدير من؟ كيف تتدفق القرارات؟', 'Who manages whom? How do decisions flow?'),
    ('المسمى الوظيفي', 'Job Title'),
    ('العدد</th>', 'Count</th>'),
    ('الراتب الشهري', 'Monthly Salary'),
    ('إجمالي شهري', 'Monthly Total'),
    ('مدير', 'Manager'),
    ('موظف', 'Employee'),
    ('إجمالي الرواتب الشهرية:', 'Total Monthly Salaries:'),
    ('ريال/شهر', 'SAR/month'),
    ('إجمالي الموظفين', 'Total Employees'),
    ('نسبة الرواتب/الإيرادات', 'Salary/Revenue Ratio'),
    ('سيُحسب', 'Will be calculated'),
    # Page 9 Technical
    ('نموذج دراسة الجدوى — التقني', 'Feasibility Study — Technical'),
    ('الاحتياجات التقنية والمعدات', 'Technical Needs & Equipment'),
    ('ما تحتاجه لتشغيل المشروع', 'What you need to run the project'),
    ('المعدة/الأداة', 'Equipment/Tool'),
    ('العدد</th>', 'Qty</th>'),
    ('سعر الوحدة', 'Unit Price'),
    ('الإجمالي</th>', 'Total</th>'),
    ('طريقة التوريد', 'Supply Method'),
    ('شراء/إيجار', 'Buy/Rent'),
    ('إجمالي تكلفة المعدات:', 'Total Equipment Cost:'),
    ('الأنظمة التقنية المطلوبة', 'Required Technical Systems'),
    ('POS، نظام إدارة المخزون، CRM، موقع إلكتروني، تطبيق...', 'POS, inventory management, CRM, website, app...'),
    # Page 10 Fixed Costs
    ('نموذج دراسة الجدوى — التكاليف الثابتة', 'Feasibility Study — Fixed Costs'),
    ('التكاليف الثابتة الشهرية', 'Monthly Fixed Costs'),
    ('التكاليف التي لا تتغير مع حجم الإنتاج', 'Costs that do not change with production volume'),
    ('بند التكلفة', 'Cost Item'),
    ('المبلغ الشهري (ريال)', 'Monthly Amount (SAR)'),
    ('الإيجار', 'Rent'),
    ('الرواتب', 'Salaries'),
    ('المرافق', 'Utilities'),
    ('اشتراكات تقنية', 'Tech Subscriptions'),
    ('رسوم تراخيص', 'License Fees'),
    ('إجمالي التكاليف الثابتة:', 'Total Fixed Costs:'),
    # Page 11 Variable Costs
    ('نموذج دراسة الجدوى — التكاليف المتغيرة', 'Feasibility Study — Variable Costs'),
    ('التكاليف المتغيرة (لكل وحدة)', 'Variable Costs (Per Unit)'),
    ('التكاليف التي تتناسب مع حجم الإنتاج', 'Costs that scale with production volume'),
    ('بند التكلفة', 'Cost Item'),
    ('للوحدة (ريال)', 'Per Unit (SAR)'),
    ('مواد خام', 'Raw Materials'),
    ('تغليف', 'Packaging'),
    ('عمولات منصات', 'Platform Commissions'),
    ('رسوم توصيل', 'Delivery Fees'),
    ('إجمالي التكلفة المتغيرة للوحدة:', 'Total Variable Cost Per Unit:'),
    # Page 12 Revenue
    ('نموذج دراسة الجدوى — الإيرادات', 'Feasibility Study — Revenue'),
    ('الإيرادات المتوقعة', 'Expected Revenue'),
    ('مصادر الدخل الشهرية المستهدفة', 'Targeted monthly income sources'),
    ('بند الإيراد', 'Revenue Item'),
    ('الكمية/شهر', 'Qty/Month'),
    ('سعر الوحدة', 'Unit Price'),
    ('الإجمالي</th>', 'Total</th>'),
    ('إجمالي الإيرادات الشهرية:', 'Total Monthly Revenue:'),
    # Page 13 Cash Flow
    ('نموذج دراسة الجدوى — التدفق النقدي', 'Feasibility Study — Cash Flow'),
    ('التدفق النقدي المتوقع (12 شهر)', 'Expected Cash Flow (12 Months)'),
    ('الأموال الداخلة والخارجة شهرياً', 'Money in and out monthly'),
    ('الشهر</th>', 'Month</th>'),
    ('الإيرادات</th>', 'Revenue</th>'),
    ('التكاليف</th>', 'Costs</th>'),
    ('صافي التدفق', 'Net Flow'),
    ('الرصيد التراكمي', 'Cumulative Balance'),
    ('💡 املأ أول 3 أشهر يدوياً، ثم اضغط "ملء تلقائي" لتوزيع بقية السنة', '💡 Fill first 3 months manually, then click "Auto Fill" for the rest of the year'),
    ('✨ ملء تلقائي من الإيرادات', '✨ Auto Fill from Revenue'),
    # Page 14 Financial Analysis
    ('نموذج دراسة الجدوى — التحليل المالي', 'Feasibility Study — Financial Analysis'),
    ('التحليل المالي الشامل', 'Comprehensive Financial Analysis'),
    ('الأرقام التي تحدد قرار الاستثمار', 'Numbers that determine the investment decision'),
    ('إجمالي التكاليف الثابتة/شهر', 'Total Fixed Costs/Month'),
    ('إجمالي التكاليف المتغيرة/شهر', 'Total Variable Costs/Month'),
    ('إجمالي الإيرادات/شهر', 'Total Revenue/Month'),
    ('صافي الربح/شهر (ريال)', 'Net Profit/Month (SAR)'),
    ('هامش الربح (%)', 'Profit Margin (%)'),
    ('نقطة التعادل (وحدة/شهر)', 'Break-Even (Units/Month)'),
    ('رأس المال المستثمر (ريال)', 'Invested Capital (SAR)'),
    ('فترة الاسترداد (شهر)', 'Payback Period (months)'),
    ('سيُحسب', 'Will be calculated'),
    ('العائد على الاستثمار ROI (%)', 'Return on Investment ROI (%)'),
    ('السيناريوهات المالية', 'Financial Scenarios'),
    ('المتشائم (-30%)', 'Pessimistic (-30%)'),
    ('صافي ربح شهري', 'Monthly Net Profit'),
    ('المتوقع</div>', 'Expected</div>'),
    ('المتفائل (+30%)', 'Optimistic (+30%)'),
    # Page 15 Sensitivity
    ('نموذج دراسة الجدوى — الحساسية', 'Feasibility Study — Sensitivity'),
    ('التحليل الحساسي والمؤشرات', 'Sensitivity Analysis & Indicators'),
    ('ماذا لو تغيرت المتغيرات الرئيسية؟', 'What if key variables change?'),
    ('تحليل الحساسية (±10%)', 'Sensitivity Analysis (±10%)'),
    ('المتغير</th>', 'Variable</th>'),
    ('-10%</th>', '-10%</th>'),
    ('الأساسي</th>', 'Base</th>'),
    ('+10%</th>', '+10%</th>'),
    ('السعر', 'Price'),
    ('الكمية المباعة', 'Quantity Sold'),
    ('التكاليف الثابتة', 'Fixed Costs'),
    ('التكاليف المتغيرة', 'Variable Costs'),
    ('المؤشرات الرئيسية للأداء (KPIs)', 'Key Performance Indicators (KPIs)'),
    ('المؤشر</th>', 'Indicator</th>'),
    ('الهدف</th>', 'Target</th>'),
    ('الواقع</th>', 'Actual</th>'),
    ('ملاحظات</th>', 'Notes</th>'),
    ('معدل رضا العملاء', 'Customer Satisfaction Rate'),
    ('معدل تكرار الشراء', 'Repeat Purchase Rate'),
    ('تكلفة اكتساب عميل (CAC)', 'Customer Acquisition Cost (CAC)'),
    ('قيمة العميل مدى الحياة (LTV)', 'Customer Lifetime Value (LTV)'),
    ('معدل دوران المخزون', 'Inventory Turnover Rate'),
    ('+ إضافة KPI', '+ Add KPI'),
    ('- حذف', '- Remove'),
    # Page 16 Risks
    ('نموذج دراسة الجدوى — المخاطر', 'Feasibility Study — Risks'),
    ('المخاطر وخطط التخفيف', 'Risks & Mitigation Plans'),
    ('حدد المخاطر مبكراً واستعد لها', 'Identify risks early and prepare for them'),
    ('الخطر</th>', 'Risk</th>'),
    ('الاحتمالية</th>', 'Likelihood</th>'),
    ('التأثير</th>', 'Impact</th>'),
    ('خطة التخفيف</th>', 'Mitigation Plan</th>'),
    ('تراجع الطلب', 'Demand Decline'),
    ('متوسط', 'Medium'),
    ('عالي', 'High'),
    ('تنويع المنتجات', 'Diversify Products'),
    ('ارتفاع التكاليف', 'Rising Costs'),
    ('عالي', 'High'),
    ('متوسط', 'Medium'),
    ('عقود ثابتة مع الموردين', 'Fixed Contracts with Suppliers'),
    ('منافس جديد', 'New Competitor'),
    ('بناء ولاء العملاء', 'Build Customer Loyalty'),
    ('تغير تنظيمي', 'Regulatory Change'),
    ('منخفض', 'Low'),
    ('متابعة القوانين', 'Monitor Laws'),
    ('خطة الطوارئ (Plan B)', 'Emergency Plan (Plan B)'),
    ('ماذا ستفعل إن فشل المشروع في تحقيق أهدافه خلال 6 أشهر؟', 'What will you do if the project fails to meet goals within 6 months?'),
    # Page 17 Quality
    ('نموذج دراسة الجدوى — الجودة', 'Feasibility Study — Quality'),
    ('الجودة والاستدامة وخطة الخروج', 'Quality, Sustainability & Exit Plan'),
    ('معايير الجودة والتأثير الاجتماعي/البيئي', 'Quality standards and social/environmental impact'),
    ('معايير الجودة', 'Quality Standards'),
    ('كيف تضمن جودة المنتج/الخدمة؟ فحوصات، شكاوى العملاء، تحسين مستمر...', 'How do you ensure product/service quality? Inspections, complaints, continuous improvement...'),
    ('التأثير الاجتماعي والبيئي (ESG)', 'Social & Environmental Impact (ESG)'),
    ('توظيف محلي، تقليل الهدر، التغليف المستدام، المسؤولية المجتمعية...', 'Local hiring, waste reduction, sustainable packaging, community responsibility...'),
    ('خطة الخروج (Exit Strategy)', 'Exit Strategy'),
    ('البيع، الدمج، التوسع، التصفية... متى وكيف؟', 'Sale, merger, expansion, liquidation... when and how?'),
    ('الأهداف الاجتماعية', 'Social Goals'),
    ('وظائف، تدريب، دعم المجتمع...', 'Jobs, training, community support...'),
    ('الأهداف البيئية', 'Environmental Goals'),
    ('تقليل الكربون، إعادة التدوير...', 'Carbon reduction, recycling...'),
    # Page 18 Capital
    ('نموذج دراسة الجدوى — رأس المال', 'Feasibility Study — Capital'),
    ('متطلبات رأس المال والنتائج', 'Capital Requirements & Results'),
    ('الاستثمار الأولي والقرار النهائي', 'Initial investment and final decision'),
    ('الاستثمار الأولي', 'Initial Investment'),
    ('بند الاستثمار', 'Investment Item'),
    ('المبلغ (ريال)', 'Amount (SAR)'),
    ('تراخيص وتسجيل', 'Licenses & Registration'),
    ('تأثيث ومعدات', 'Furniture & Equipment'),
    ('تجهيز الموقع', 'Site Preparation'),
    ('مخزون أولي', 'Initial Inventory'),
    ('تسويق إطلاق', 'Launch Marketing'),
    ('رأس مال تشغيلي (3 أشهر)', 'Working Capital (3 months)'),
    ('إجمالي رأس المال المطلوب', 'Total Required Capital'),
    ('المصدر المتوقع', 'Expected Source'),
    ('تمويل ذاتي / قرض / مستثمر / منصة', 'Self-funded / Loan / Investor / Platform'),
    ('استراتيجية التمويل', 'Financing Strategy'),
    ('كيف ستؤمن التمويل؟ بأي شروط؟ متى؟', 'How will you secure funding? Under what terms? When?'),
    ('النتائج الرئيسية', 'Key Results'),
    ('أهم ما توصلت إليه من الدراسة...', 'Key findings from the study...'),
    ('التوصيات والخطوات التالية', 'Recommendations & Next Steps'),
    ('ما الخطوة الأولى؟ من يبدأها؟ متى؟', 'What is the first step? Who starts it? When?'),
    ('هل المشروع مجدي؟', 'Is the project viable?'),
    ('اختر...', 'Select...'),
    ('✅ نعم، مجدي', '✅ Yes, Viable'),
    ('❌ لا، غير مجدي', '❌ No, Not Viable'),
    ('⚠️ مجدي بشروط', '⚠️ Viable Under Conditions'),
    ('إعداد وتوقيع', 'Prepared & Signed'),
    ('التاريخ</label>', 'Date</label>'),
    # Footer
    ('هذا النموذج مقدم من', 'This template is provided by'),
    ('كأداة مساعدة فقط. لا يُعتبر استشارة مالية أو قانونية.', 'as an assistive tool only. Not financial or legal advice.'),
    ('للحصول على دراسة جدوى مفصلة،', 'For a detailed feasibility study,'),
    ('احجز استشارتك', 'book your consultation'),
    ('&copy; 2026 بوندز. جميع الحقوق محفوظة.', '&copy; 2026 Bonds. All rights reserved.'),
    # Print header
    ('نموذج دراسة الجدوى المتكامل', 'Integrated Feasibility Study'),
    ('نموذج دراسة الجدوى — الرؤية', 'Feasibility Study — Vision'),
    ('نموذج دراسة الجدوى — الملخص', 'Feasibility Study — Summary'),
    ('نموذج دراسة الجدوى — المنتجات', 'Feasibility Study — Products'),
    ('نموذج دراسة الجدوى — تحليل السوق', 'Feasibility Study — Market Analysis'),
    ('نموذج دراسة الجدوى — التسويق', 'Feasibility Study — Marketing'),
    ('نموذج دراسة الجدوى — التشغيل', 'Feasibility Study — Operations'),
    ('نموذج دراسة الجدوى — القانون', 'Feasibility Study — Legal'),
    ('نموذج دراسة الجدوى — الموارد البشرية', 'Feasibility Study — HR'),
    ('نموذج دراسة الجدوى — التقني', 'Feasibility Study — Technical'),
    ('نموذج دراسة الجدوى — التكاليف الثابتة', 'Feasibility Study — Fixed Costs'),
    ('نموذج دراسة الجدوى — التكاليف المتغيرة', 'Feasibility Study — Variable Costs'),
    ('نموذج دراسة الجدوى — الإيرادات', 'Feasibility Study — Revenue'),
    ('نموذج دراسة الجدوى — التدفق النقدي', 'Feasibility Study — Cash Flow'),
    ('نموذج دراسة الجدوى — التحليل المالي', 'Feasibility Study — Financial Analysis'),
    ('نموذج دراسة الجدوى — الحساسية', 'Feasibility Study — Sensitivity'),
    ('نموذج دراسة الجدوى — المخاطر', 'Feasibility Study — Risks'),
    ('نموذج دراسة الجدوى — الجودة', 'Feasibility Study — Quality'),
    ('نموذج دراسة الجدوى — رأس المال', 'Feasibility Study — Capital'),
    # CSS
    ('text-align: right;', 'text-align: left;'),
    # Nav links
    ('href="../index.html"', 'href="../../index.html"'),
    ('href="../about.html"', 'href="../../about.html"'),
    ('href="../services.html', 'href="../../services.html'),
    ('href="../calculator.html"', 'href="../../calculator.html"'),
    ('href="../blog/index.html"', 'href="../../blog/index.html"'),
    ('href="../faq.html"', 'href="../../faq.html"'),
    ('href="../contact.html"', 'href="../../contact.html"'),
    ('href="cash-flow.html"', 'href="cash-flow.html"'),
    ('href="pricing.html"', 'href="pricing.html"'),
    ('href="loan.html"', 'href="loan.html"'),
    ('href="restaurant.html"', 'href="restaurant.html"'),
    ('href="menu-engineering.html"', 'href="menu-engineering.html"'),
    ('href="feasibility.html"', 'href="feasibility.html"'),
    ('href="invoice-analyzer.html"', 'href="invoice-analyzer.html"'),
    ('href="feasibility-template.html"', 'href="feasibility-template.html"'),
    ('href="../en/calculators/feasibility-template.html"', 'href="../../calculators/feasibility-template.html"'),
    ('href="../assets/', 'href="../../assets/'),
    ('href="../styles.css"', 'href="../../styles.css"'),
    ('src="../assets/', 'src="../../assets/'),
]

replacements.sort(key=lambda x: len(x[0]), reverse=True)
for old, new in replacements:
    content = content.replace(old, new)

with open('en/calculators/feasibility-template.html', 'w', encoding='utf-8') as f:
    f.write(content)

print("Done! Translated", len(replacements), "strings.")
