#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Translate feasibility-template.html from AR to EN"""

replacements = {
    # HTML attrs
    'lang="ar" dir="rtl"': 'lang="en" dir="ltr"',
    'dir="rtl"': 'dir="ltr"',
    # Fonts
    "'Vazirmatn'": "'Inter'",
    # Title & meta
    'نموذج دراسة الجدوى | بوندز — املأ واطبع': 'Feasibility Study Template | Bonds — Fill & Print',
    'نموذج دراسة جدوى احترافي لتعبئة المعلومات وطباعتها. مجاني من بوندز.': 'Professional feasibility study template for filling and printing. Free from Bonds.',
    'نموذج دراسة الجدوى | بوندز': 'Feasibility Study Template | Bonds',
    'نموذج دراسة جدوى احترافي لتعبئة المعلومات وطباعتها.': 'Professional feasibility study template for filling and printing.',
    # Nav
    'الرئيسية': 'Home',
    'عن بوندز': 'About',
    'الخدمات': 'Services',
    'التحليل المالي': 'Financial Analysis',
    'إدارة التدفقات النقدية': 'Cash Flow Management',
    'دراسات الجدوى': 'Feasibility Studies',
    'نقطة التعادل': 'Break-Even',
    'الحاسبات': 'Calculators',
    'تدفق النقد': 'Cash Flow',
    'تسعير المنتج': 'Product Pricing',
    'القرض والتمويل': 'Loan & Finance',
    'المطاعم والسحابي': 'Restaurants & Cloud',
    'هندسة المنيو': 'Menu Engineering',
    'جدوى المطعم': 'Restaurant Feasibility',
    'تحليل الفواتير': 'Invoice Analyzer',
    'نموذج دراسة الجدوى': 'Feasibility Study Template',
    'المدونة': 'Blog',
    'الأسئلة الشائعة': 'FAQ',
    'تواصل معنا': 'Contact Us',
    'EN': 'AR',
    'تبديل الوضع': 'Toggle Theme',
    'القائمة': 'Menu',
    'تسجيل الدخول': 'Login',
    # Toolbar
    'طباعة / PDF': 'Print / PDF',
    'مسح الكل': 'Clear All',
    'حفظ مسودة': 'Save Draft',
    'استرجاع مسودة': 'Load Draft',
    'تم حفظ المسودة بنجاح ✅': 'Draft saved successfully ✅',
    'لا توجد مسودة محفوظة': 'No saved draft found',
    'تم استرجاع المسودة ✅': 'Draft loaded successfully ✅',
    'هل أنت متأكد من مسح جميع البيانات؟': 'Are you sure you want to clear all data?',
    # Cover
    'نموذج دراسة الجدوى': 'Feasibility Study Template',
    'Feasibility Study Template': 'Feasibility Study Template',
    'اسم النشاط التجاري': 'Business Name',
    'مثال: مطعم الذواقة': 'e.g. Al-Thawaqa Restaurant',
    'اسم صاحب النشاط': 'Owner Name',
    'الاسم الكامل': 'Full Name',
    'الشكل القانوني': 'Legal Form',
    'مؤسسة فردية / شركة ذات مسؤولية محدودة': 'Sole Proprietorship / LLC',
    'تاريخ الإعداد': 'Preparation Date',
    'فكرة النشاط': 'Business Idea',
    'وصف مختصر لفكرة المشروع...': 'Brief description of the project idea...',
    'سبب اختيار الفكرة': 'Reason for Choosing This Idea',
    'لماذا اخترت هذا المشروع تحديداً؟': 'Why did you choose this specific project?',
    # Section 1
    'نموذج دراسة الجدوى — الشركاء': 'Feasibility Study — Partners',
    'معلومات الشركاء': 'Partner Information',
    'بيانات الشركاء (إن وجدوا) ونسب ملكيتهم وأدوارهم': 'Partner details (if any), ownership percentages, and roles',
    'م': '#',
    'اسم الشريك': 'Partner Name',
    'الدور': 'Role',
    'نسبة الملكية (%)': 'Ownership (%)',
    'إضافة صف': 'Add Row',
    'حذف صف': 'Remove Row',
    # Section 2
    'نموذج دراسة الجدوى — الملخص التنفيذي': 'Feasibility Study — Executive Summary',
    'الملخص التنفيذي': 'Executive Summary',
    'نظرة عامة على محتوى دراسة الجدوى (يُفضل كتابته بعد إتمام الأجزاء الأخرى)': 'Overview of the feasibility study content (best written after completing other sections)',
    'ملخص المشروع': 'Project Summary',
    'قدم نظرة شاملة على المشروع: الفكرة، السوق، الفرصة، والنتائج المتوقعة...': 'Provide a comprehensive overview: idea, market, opportunity, and expected results...',
    'رأس المال المطلوب (ريال)': 'Required Capital (SAR)',
    'فترة الاسترداد المتوقعة (شهر)': 'Expected Payback Period (months)',
    'العائد على الاستثمار المتوقع (%)': 'Expected ROI (%)',
    'عدد الوظائف المتوقعة': 'Expected Jobs',
    # Section 3
    'نموذج دراسة الجدوى — المنتجات': 'Feasibility Study — Products',
    'وصف المنتجات والخدمات': 'Products & Services Description',
    'وصف تفصيلي لما ستقدمه وكيف يستفيد منه العملاء والشركة': 'Detailed description of what you will offer and how customers and the company benefit',
    'ما هي المنتجات أو الخدمات التي ستقدمها؟': 'What products or services will you offer?',
    'صف كل منتج/خدمة بوضوح...': 'Describe each product/service clearly...',
    'جدول المنتجات والمميزات': 'Products & Features Table',
    'اسم المنتج/الخدمة': 'Product/Service Name',
    'المميزات الفريدة': 'Unique Features',
    'القيمة المضافة للمنتجات/الخدمات': 'Added Value',
    'ما الذي يميز منتجك عن المنافسين؟': 'What differentiates your product from competitors?',
    'كيف سيستفيد العملاء من منتجاتك/خدماتك؟': 'How will customers benefit from your products/services?',
    'الفائدة المباشرة للعميل...': 'Direct customer benefit...',
    # Section 4
    'نموذج دراسة الجدوى — التكنولوجيا': 'Feasibility Study — Technology',
    'التأثير التكنولوجي': 'Technological Impact',
    'هل للتكنولوجيا تأثير إيجابي أو سلبي على نشاطك؟': 'Will technology have positive or negative effects on your business?',
    'هل للتكنولوجيا تأثيرات سلبية على منتجاتك/خدماتك؟': 'Will technology have negative effects on your products/services?',
    'اشرح التأثيرات السلبية إن وجدت...': 'Explain negative effects if any...',
    'هل للتكنولوجيا تأثيرات إيجابية على منتجاتك/خدماتك؟': 'Will technology have positive effects on your products/services?',
    'اشرح التأثيرات الإيجابية...': 'Explain positive effects...',
    'هل ستتأثر منتجاتك/خدماتك بالتكنولوجيا في المستقبل القريب؟': 'Will your products/services be affected by technology in the near future?',
    'التوقعات المستقبلية...': 'Future expectations...',
    'كيف ستستخدم التكنولوجيا لصالحك وتحقيق الاستفادة منها؟': 'How will you use technology to your advantage?',
    'خطتك للاستفادة من التكنولوجيا...': 'Your plan to leverage technology...',
    # Section 5
    'نموذج دراسة الجدوى — الاقتصاد': 'Feasibility Study — Economy',
    'الاقتصاد العام': 'General Economy',
    'الوضع الاقتصادي العام والتوقعات': 'Overall economic situation and expectations',
    'ما هو الوضع الاقتصادي العام في آخر ثلاث سنوات؟': 'What is the overall economic situation in the last three years?',
    'وصف الحالة الاقتصادية...': 'Describe the economic situation...',
    'ما هو ميزانية الدولة في السنوات السابقة والحالية؟ (الإنفاق العام، الإيرادات، الفائض أو العجز)': 'What is the state budget in previous and current years? (Public spending, revenues, surplus or deficit)',
    'البيانات المالية الحكومية...': 'Government financial data...',
    'هل الاقتصاد في تراجع، نمو، أم استقرار؟': 'Is the economy declining, growing, or stable?',
    'وصف حالة الاقتصاد...': 'Describe the economy...',
    'ما هو الناتج المحلي الإجمالي (GDP) لآخر ثلاث سنوات؟': 'What is the GDP for the last three years?',
    'بيانات الناتج المحلي...': 'GDP data...',
    'ما هي القدرة الشرائية للأفراد؟': 'What is the purchasing power of individuals?',
    'تقييم القدرة الشرائية...': 'Purchasing power assessment...',
    'ما هي التوقعات الاقتصادية للسوق؟': 'What are the economic expectations for the market?',
    'التوقعات المستقبلية...': 'Future expectations...',
    # Section 6
    'نموذج دراسة الجدوى — السوق': 'Feasibility Study — Market',
    'سوق المنتج أو الخدمة': 'Product or Service Market',
    'الجمهور المستهدف، المنافسون، وأسباب اختيار العملاء لك': 'Target audience, competitors, and why customers will choose you',
    'من هو الجمهور المستهدف؟': 'Who is the target audience?',
    'وصف الجمهور المستهدف (عمر، دخل، موقع جغرافي، اهتمامات)...': 'Describe target audience (age, income, location, interests)...',
    'حجم السوق المحلي (تقدير)': 'Local Market Size (estimate)',
    'مثال: 50 مليون ريال': 'e.g. 50 million SAR',
    'حجم السوق المستورد (تقدير)': 'Imported Market Size (estimate)',
    'مثال: 20 مليون ريال': 'e.g. 20 million SAR',
    'إجمالي حجم السوق': 'Total Market Size',
    'المحلي + المستورد': 'Local + Imported',
    'ما نسبة السوق من المنتجات المحلية؟ وما نسبة المستوردة؟': 'What is the local vs imported product market share?',
    'كيف كان الطلب في السنوات السابقة؟ هل الطلب أكبر من العرض أم العكس؟': 'How was demand in previous years? Is demand greater than supply or vice versa?',
    'تحليل العرض والطلب...': 'Supply and demand analysis...',
    'ما الذي يحفز العملاء على الشراء؟': 'What motivates customers to purchase?',
    'عوامل تحفيز الشراء...': 'Purchase motivators...',
    'لماذا سيختار العملاء منتجاتك/خدماتك بدلاً عن المنافسين؟': 'Why will customers choose your products/services over competitors?',
    'مميزاتك التنافسية...': 'Your competitive advantages...',
    'المنافسون المحتملون': 'Potential Competitors',
    'اسم المنافس': 'Competitor Name',
    'نقاط القوة': 'Strengths',
    'نقاط الضعف': 'Weaknesses',
    # Section 7
    'نموذج دراسة الجدوى — التسويق': 'Feasibility Study — Marketing',
    'استراتيجية التسويق': 'Marketing Strategy',
    'كيف ستصل إلى جمهورك المستهدف وت differentiate نفسك': 'How you will reach your target audience and differentiate yourself',
    'ما هي وسائل التسويق التي ستستخدمها؟': 'What marketing methods will you use?',
    'وسائل التواصل الاجتماعي، الإعلانات المدفوعة، التسويق بالمحتوى، الشراكات...': 'Social media, paid ads, content marketing, partnerships...',
    'هل تتوافق وسائل التسويق مع الجمهور المستهدف؟': 'Do marketing methods align with the target audience?',
    'شرح التوافق...': 'Explain alignment...',
    'كيف ستتميز عن منافسيك؟': 'How will you differentiate from competitors?',
    'استراتيجية التمايز...': 'Differentiation strategy...',
    'ميزانية التسويق الشهرية (تقدير)': 'Monthly Marketing Budget (estimate)',
    'نسبة تكلفة اكتساب العميل (CAC)': 'Customer Acquisition Cost (CAC)',
    # Section 8
    'نموذج دراسة الجدوى — الموارد البشرية': 'Feasibility Study — Human Resources',
    'النشاط والموارد البشرية': 'Business Activity & Human Resources',
    'القوى العاملة المطلوبة والهيكل التنظيمي': 'Required workforce and organizational structure',
    'الموظفون المطلوبون في أول 3 أشهر': 'Employees Needed in First 3 Months',
    'المسمى الوظيفي': 'Job Title',
    'العدد': 'Count',
    'الراتب الشهري': 'Monthly Salary',
    'الموظفون المطلوبون في أول 6 أشهر': 'Employees Needed in First 6 Months',
    'الموظفون المطلوبون في أول سنة': 'Employees Needed in First Year',
    'الهيكل التنظيمي للنشاط': 'Organizational Structure',
    'صف الهيكل التنظيمي: من يشرف على من، كيف تتدفق القرارات...': 'Describe the org structure: who reports to whom, decision flow...',
    'المؤهلات المطلوبة لكل وظيفة': 'Required Qualifications',
    'المؤهلات العلمية والخبرات المطلوبة...': 'Academic qualifications and required experience...',
    'المسؤوليات المحددة لكل موظف': 'Specific Employee Responsibilities',
    'الأدوار والمهام...': 'Roles and tasks...',
    # Section 9
    'نموذج دراسة الجدوى — الجدول الزمني': 'Feasibility Study — Timeline',
    'الجدول الزمني': 'Timeline',
    'معالم رئيسية وتواريخ مستهدفة': 'Key milestones and target dates',
    'المهمة': 'Task',
    'التاريخ المتوقع / الموعد النهائي': 'Expected Date / Deadline',
    'الحالة': 'Status',
    'إتمام خطة العمل التشغيلية': 'Completion of Operational Business Plan',
    'قيد التنفيذ': 'In Progress',
    'الحصول على التمويل': 'Funding Acquisition',
    'بدء التوظيف': 'Start of Hiring',
    'الافتتاح التجريبي': 'Trial Opening',
    'الافتتاح الرسمي': 'Grand Opening',
    # Section 10
    'نموذج دراسة الجدوى — القسم التقني': 'Feasibility Study — Technical Section',
    'القسم التقني': 'Technical Section',
    'نظرة عامة على عملية الإنتاج/التشغيل': 'Overview of production/operation process',
    'أين يقع النشاط التجاري؟': 'Where is the business located?',
    'الموقع الجغرافي، مدينة، حي...': 'Geographic location, city, district...',
    'هل الموقع مناسب وقريب من الجمهور المستهدف؟': 'Is the location suitable and close to the target audience?',
    'تحليل موقع المشروع...': 'Location analysis...',
    'المواد المطلوبة للإنتاج': 'Required Production Materials',
    'المادة': 'Material',
    'طريقة التوريد': 'Supply Method',
    'الموردون': 'Suppliers',
    'الأدوات والآلات المطلوبة': 'Required Tools & Machinery',
    'الأداة / الآلة': 'Tool / Machine',
    'التأثير المتوقع للقرارات الحكومية على النشاط (مثل الرسوم البلدية وضريبة القيمة المضافة)': 'Expected impact of government decisions (e.g. municipal fees, VAT)',
    'تحليل التأثيرات التنظيمية...': 'Regulatory impact analysis...',
    # Section 11
    'نموذج دراسة الجدوى — نموذج العمل': 'Feasibility Study — Business Model',
    'نموذج العمل': 'Business Model',
    'كيف تُحقق الأرباح والقيمة المضافة': 'How you generate profits and added value',
    'كيف ستُحقق الأرباح؟': 'How will you generate profits?',
    'مصادر الدخل، نموذج التسعير، هامش الربح...': 'Revenue sources, pricing model, profit margin...',
    'ما هي القيم الأخرى التي ستُحققها بجانب الأرباح؟': 'What other values will you achieve besides profits?',
    'القيمة الاجتماعية، الوظائف، التأثير البيئي...': 'Social value, jobs, environmental impact...',
    'شرح نموذج العمل (Business Model Canvas)': 'Business Model Canvas Explanation',
    'الشركاء الرئيسيون، الأنشطة الأساسية، الموارد، عرض القيمة، علاقات العملاء، القنوات، شرائح العملاء، هيكل التكاليف، مصادر الإيرادات...': 'Key partners, key activities, resources, value proposition, customer relationships, channels, customer segments, cost structure, revenue streams...',
    # Section 12
    'نموذج دراسة الجدوى — المخاطر': 'Feasibility Study — Risks',
    'عوامل الخطر العامة': 'General Risk Factors',
    'تحديد المخاطر المحتملة وخطط التخفيف': 'Identify potential risks and mitigation plans',
    'الخطر': 'Risk',
    'احتمالية الحدوث': 'Likelihood',
    'التأثير': 'Impact',
    'خطة التخفيف': 'Mitigation Plan',
    'عالي/متوسط/منخفض': 'High/Medium/Low',
    'كبير/متوسط/صغير': 'Major/Medium/Minor',
    # Section 13
    'نموذج دراسة الجدوى — القدرات': 'Feasibility Study — Capabilities',
    'القدرات والكفاءات': 'Capabilities & Competencies',
    'نقاط القوة التي تمتلكها لإنجاح المشروع': 'Strengths you have to make the project successful',
    'هل لديك خبرة سابقة في نفس المجال؟': 'Do you have prior experience in the same field?',
    'الخبرات السابقة...': 'Previous experience...',
    'هل لديك فريق عمل مؤهل؟': 'Do you have a qualified team?',
    'تفاصيل الفريق...': 'Team details...',
    'هل لديك شبكة علاقات في السوق؟': 'Do you have a network of relationships in the market?',
    'العلاقات المهنية...': 'Professional relationships...',
    'هل لديك ميزانية تكفي للبداية؟': 'Do you have sufficient budget to start?',
    'وضع التمويل...': 'Financing status...',
    'هل لديك موقع/مكان مناسب للعمل؟': 'Do you have a suitable location for the business?',
    'وصف الموقع...': 'Location description...',
    # Section 14
    'نموذج دراسة الجدوى — التوقعات المالية': 'Feasibility Study — Financial Expectations',
    'التوقعات المالية': 'Financial Expectations',
    'التكاليف، الإيرادات، والأرباح المتوقعة': 'Costs, revenues, and expected profits',
    'التكاليف الثابتة (شهرية)': 'Fixed Costs (Monthly)',
    'بند التكلفة': 'Cost Item',
    'المبلغ الشهري (ريال)': 'Monthly Amount (SAR)',
    'الإيجار': 'Rent',
    'الرواتب': 'Salaries',
    'المرافق (كهرباء، ماء، إنترنت)': 'Utilities (Electricity, Water, Internet)',
    'التأمين': 'Insurance',
    'رسوم تراخيص': 'License Fees',
    'التكاليف المتغيرة (للوحدة)': 'Variable Costs (Per Unit)',
    'المبلغ (ريال)': 'Amount (SAR)',
    'مواد خام': 'Raw Materials',
    'تغليف': 'Packaging',
    'عمولات منصات': 'Platform Commissions',
    'رسوم توصيل': 'Delivery Fees',
    'الإيرادات المتوقعة (شهرية)': 'Expected Revenue (Monthly)',
    'بند الإيراد': 'Revenue Item',
    'الكمية الشهرية': 'Monthly Quantity',
    'سعر الوحدة': 'Unit Price',
    'الإجمالي': 'Total',
    'إجمالي التكاليف الشهرية (تقدير)': 'Total Monthly Costs (estimate)',
    'إجمالي الإيرادات الشهرية (تقدير)': 'Total Monthly Revenue (estimate)',
    'صافي الربح الشهري المتوقع': 'Expected Monthly Net Profit',
    'هامش الربح (%)': 'Profit Margin (%)',
    # Section 15
    'نموذج دراسة الجدوى — رأس المال': 'Feasibility Study — Capital',
    'متطلبات رأس المال': 'Capital Requirements',
    'الاستثمار الأولي واستراتيجية التمويل': 'Initial investment and financing strategy',
    'الاستثمار الأولي': 'Initial Investment',
    'بند الاستثمار': 'Investment Item',
    'المبلغ (ريال)': 'Amount (SAR)',
    'تراخيص وتسجيل': 'Licenses & Registration',
    'تأثيث ومعدات': 'Furniture & Equipment',
    'تجهيز الموقع': 'Site Preparation',
    'مخزون أولي': 'Initial Inventory',
    'تسويق إطلاق': 'Launch Marketing',
    'رأس مال تشغيلي (3 أشهر)': 'Working Capital (3 months)',
    'إجمالي رأس المال المطلوب': 'Total Required Capital',
    'المصدر المتوقع للتمويل': 'Expected Funding Source',
    'تمويل ذاتي / قرض / مستثمر': 'Self-funded / Loan / Investor',
    'استراتيجية التمويل': 'Financing Strategy',
    'كيف ستؤمن التمويل؟ متى؟ بأي شروط؟': 'How will you secure funding? When? Under what terms?',
    # Section 16
    'نموذج دراسة الجدوى — النتائج': 'Feasibility Study — Results',
    'النتائج والتوصيات': 'Results & Recommendations',
    'الخلاصة النهائية والقرار': 'Final conclusion and decision',
    'هل المشروع مجدي اقتصادياً؟': 'Is the project economically viable?',
    'اختر...': 'Select...',
    'نعم، مجدي': 'Yes, viable',
    'لا، غير مجدي حالياً': 'No, not viable currently',
    'مجدي بشروط': 'Viable under conditions',
    'النتائج الرئيسية': 'Key Results',
    'أهم النتائج التي توصلت إليها من الدراسة...': 'Key findings from the study...',
    'التوصيات': 'Recommendations',
    'التوصيات العملية: ما الخطوات التالية؟ ما الذي يجب تحسينه؟': 'Practical recommendations: next steps? what needs improvement?',
    'الخطوات التالية المقترحة': 'Proposed Next Steps',
    'جدول زمني للخطوات التالية...': 'Timeline for next steps...',
    'إعداد وتوقيع': 'Prepared & Signed',
    'التاريخ': 'Date',
    # Footer
    'هذا النموذج مقدم من': 'This template is provided by',
    'كأداة مساعدة فقط. لا يُعتبر استشارة مالية أو قانونية.': 'as an assistive tool only. Not financial or legal advice.',
    'للحصول على دراسة جدوى مفصلة،': 'For a detailed feasibility study,',
    'احجز استشارتك': 'book your consultation',
    '&copy; 2026 بوندز. جميع الحقوق محفوظة.': '&copy; 2026 Bonds. All rights reserved.',
    # Cover meta print
    'نموذج دراسة الجدوى —': 'Feasibility Study —',
    # Print CSS Arabic -> English
    'right': 'left',
    'text-align: right;': 'text-align: left;',
    # Nav links fix
    'href="../index.html"': 'href="../../index.html"',
    'href="../about.html"': 'href="../../about.html"',
    'href="../services.html': 'href="../../services.html',
    'href="../calculator.html"': 'href="../../calculator.html"',
    'href="../blog/index.html"': 'href="../../blog/index.html"',
    'href="../faq.html"': 'href="../../faq.html"',
    'href="../contact.html"': 'href="../../contact.html"',
    'href="cash-flow.html"': 'href="cash-flow.html"',
    'href="pricing.html"': 'href="pricing.html"',
    'href="loan.html"': 'href="loan.html"',
    'href="restaurant.html"': 'href="restaurant.html"',
    'href="menu-engineering.html"': 'href="menu-engineering.html"',
    'href="feasibility.html"': 'href="feasibility.html"',
    'href="invoice-analyzer.html"': 'href="invoice-analyzer.html"',
    'href="feasibility-template.html"': 'href="feasibility-template.html"',
    'href="../en/calculators/feasibility-template.html"': 'href="../../calculators/feasibility-template.html"',
    'href="../assets/': 'href="../../assets/',
    'href="../styles.css"': 'href="../../styles.css"',
    'src="../assets/': 'src="../../assets/',
}

with open('en/calculators/feasibility-template.html', 'r', encoding='utf-8') as f:
    content = f.read()

for old, new in replacements.items():
    content = content.replace(old, new)

with open('en/calculators/feasibility-template.html', 'w', encoding='utf-8') as f:
    f.write(content)

print("Done! Translated", len(replacements), "strings.")
