-- AI Business Advisor — Saved executive reports
-- Stores generated management reports for audit and sharing.

CREATE TABLE IF NOT EXISTS public.ai_advisor_reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  content_html text NOT NULL,
  summary jsonb NOT NULL DEFAULT '{}',
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.ai_advisor_reports IS 'Saved executive reports generated by the AI Business Advisor module.';

CREATE INDEX IF NOT EXISTS idx_ai_advisor_reports_created_by ON public.ai_advisor_reports(created_by);
CREATE INDEX IF NOT EXISTS idx_ai_advisor_reports_created_at ON public.ai_advisor_reports(created_at DESC);

ALTER TABLE public.ai_advisor_reports ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS ai_advisor_reports_select ON public.ai_advisor_reports;
CREATE POLICY ai_advisor_reports_select ON public.ai_advisor_reports FOR SELECT TO authenticated USING (public.is_advisory_user());

DROP POLICY IF EXISTS ai_advisor_reports_insert ON public.ai_advisor_reports;
CREATE POLICY ai_advisor_reports_insert ON public.ai_advisor_reports FOR INSERT TO authenticated WITH CHECK (public.is_advisory_user() AND auth.uid() = created_by);

DROP POLICY IF EXISTS ai_advisor_reports_update ON public.ai_advisor_reports;
CREATE POLICY ai_advisor_reports_update ON public.ai_advisor_reports FOR UPDATE TO authenticated USING (public.is_advisory_user() AND auth.uid() = created_by) WITH CHECK (public.is_advisory_user() AND auth.uid() = created_by);

DROP POLICY IF EXISTS ai_advisor_reports_delete ON public.ai_advisor_reports;
CREATE POLICY ai_advisor_reports_delete ON public.ai_advisor_reports FOR DELETE TO authenticated USING (public.is_advisory_user() AND auth.uid() = created_by);

DROP TRIGGER IF EXISTS trg_ai_advisor_reports_updated_at ON public.ai_advisor_reports;
CREATE TRIGGER trg_ai_advisor_reports_updated_at BEFORE UPDATE ON public.ai_advisor_reports FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
